# Generated by Django 5.2.5 on 2025-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_course_enrollment_instructor_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
