# Generated by Django 5.2.5 on 2025-09-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emial',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
